name: Test contexts

on: [push]

jobs:
  job_1:
    name: Display contexts
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kceb/git-message-action@v1
        id: step_id_1
        with:
          sha: "context"
      - uses: kceb/git-message-action@v1
        with:
          sha: "context"    
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
