name: Test Conditon

on: [push]

jobs:
  job_1:
    name: Test conditon 1
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: step 1- continue-on-error_true 
        continue-on-error: true
        run: 1/0
      - name: step 2- continue-on-error_false
        continue-on-error: false
        run: 1/0
      - name: step 3- success
        run: echo "OK"
  job_2:
    name: Test conditon 2
    runs-on: macos-latest
    continue-on-error: false
    needs: job_1
    steps:
      - name: step 1- continue-on-error_true 
        continue-on-error: true
        run: 1/0
      - name: step 2- continue-on-error_false
        continue-on-error: true
        run: 1/0
      - name: step 3- success
        run: echo "OK"
  job_3:
    name: Test conditon 3
    runs-on: macos-latest
    needs: job_2
    steps:
      - name: step 3- success
        run: echo "OK"
