name: Test matrix

on: [push]

jobs:
  job_1:
    name: job with matrix
    runs-on: macos
    strategy:
      matrix:
        node: [6, 8, 10]
    steps:
      - uses: actions/checkout@v2
      - uses: kceb/git-message-action@v1
        id: step_id_1
        with:
          sha: 'master'
      - uses: kceb/git-message-action@v1
        id: step_id_2
        with:
          sha: 'master'
